package com.vjsoft.business.vo;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Date;


//vo前端显示层数据和pojo层数据库数据类型的转换
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class UserVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.username
     *
     * @mbg.generated
     */
    private String username;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjsoft_user.userpic
     *
     * @mbg.generated
     */
    private String userpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.id
     *
     * @return the value of vjsoft_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.id
     *
     * @param id the value for vjsoft_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.username
     *
     * @return the value of vjsoft_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.username
     *
     * @param username the value for vjsoft_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.email
     *
     * @return the value of vjsoft_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.email
     *
     * @param email the value for vjsoft_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.phone
     *
     * @return the value of vjsoft_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.phone
     *
     * @param phone the value for vjsoft_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.question
     *
     * @return the value of vjsoft_user.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.question
     *
     * @param question the value for vjsoft_user.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.answer
     *
     * @return the value of vjsoft_user.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.answer
     *
     * @param answer the value for vjsoft_user.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.role
     *
     * @return the value of vjsoft_user.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.role
     *
     * @param role the value for vjsoft_user.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.create_time
     *
     * @return the value of vjsoft_user.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.create_time
     *
     * @param createTime the value for vjsoft_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.update_time
     *
     * @return the value of vjsoft_user.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.update_time
     *
     * @param updateTime the value for vjsoft_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.ip
     *
     * @return the value of vjsoft_user.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.ip
     *
     * @param ip the value for vjsoft_user.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjsoft_user.userpic
     *
     * @return the value of vjsoft_user.userpic
     *
     * @mbg.generated
     */
    public String getUserpic() {
        return userpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjsoft_user.userpic
     *
     * @param userpic the value for vjsoft_user.userpic
     *
     * @mbg.generated
     */
    public void setUserpic(String userpic) {
        this.userpic = userpic;
    }
}