package com.vjsoft.business.dao;

import com.vjsoft.business.pojo.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjsoft_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjsoft_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjsoft_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjsoft_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjsoft_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    //判断用户名是否存在
    int findByUsername(String username);
    //用户名和密码查询
    User findByUsernameAndPassword(@Param("username") String username,@Param("password")String password);
    //判断邮箱存在
    int findByEmail(String email);

}